# version: "3.11" # DOCKER compose API version

services: # container
  app: # Django
    build:
      context: . # route
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes: # storage
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=youtube
      - DB_USER=yeringwak
      - DB_PASS=yerin123
    depends_on:
      - db

  # app: 과 같은 뎁스로
  db:
    image: postgres:16-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=youtube
      - POSTGRES_USER=yeringwak
      - POSTGRES_PASSWORD=yerin123